"""Add collections

Revision ID: 72279acb9475
Revises: cce593571d44
Create Date: 2026-06-15 10:34:22.174835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72279acb9475'
down_revision = 'cce593571d44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_collections_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_collections'))
    )
    op.create_table('collection_book',
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_collection_book_book_id_books'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], name=op.f('fk_collection_book_collection_id_collections'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('collection_id', 'book_id', name=op.f('pk_collection_book'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('collection_book')
    op.drop_table('collections')
    # ### end Alembic commands ###
