"""add rating_num and sum

Revision ID: cce593571d44
Revises: d15ec1d1e70d
Create Date: 2026-06-13 01:45:15.512823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cce593571d44'
down_revision = 'd15ec1d1e70d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating_sum', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('rating_num', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('rating_num')
        batch_op.drop_column('rating_sum')

    # ### end Alembic commands ###
